---
application:
  identity:
    url: http://localhost:9090
    clientid: clientid
    username: username
    password: password
    maxTimeForCall: 5000
    timeBetweenRetries: 1000
  # TODO: might be better do divide them by publishers and consumers
  kafka:
    reference-data:
      topic: reference-data
---
micronaut:
  application:
    name: madness-api-kafka-client
---
kafka:
  default:
    api:
      timeout:
        ms: 21600000
  bootstrap:
    servers: localhost:9092
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    adjustDatesToContextTimeZone: false
  mapper:
    acceptCaseInsensitiveProperties: true
