---
application:
  kafka:
    reference-data:
      topic: reference-data
---
micronaut:
  application:
    name: madness-api-kafka-client
---
kafka:
  default:
    api:
      timeout:
        ms: 21600000
  bootstrap:
    servers: localhost:9092
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    adjustDatesToContextTimeZone: false
  mapper:
    acceptCaseInsensitiveProperties: true
